apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  serviceAccount: bob
  arguments:
    parameters:
      - name: environment
        value: sesmorts
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: python:alpine3.6
      command: ["python", -c]
      args: ["import this;"]
    metrics:
      prometheus:
        - name: workflow_failed_count
          help: help:Count workflows with 'Failed' status
          labels:
            - key: workflow_template
              value: create-sandbox
            - key: status
              value: '{{status}}'
            - key: sandbox_name
              value: '{{workflow.parameters.environment}}'
          when: '{{status}} == Failed'
          counter:
            value: "1"
        - name: workflow_duration_seconds
          labels:
            - key: workflow_template
              value: create-sandbox
            - key: status
              value: '{{status}}'
            - key: sandbox_name
              value: '{{workflow.parameters.environment}}'
          help: Duration of the workflow (in seconds)
          gauge:
            realtime: false
            value: "{{workflow.duration}}"
