apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
      filters:
        data:
          - path: body.action
            type: string
            value:
              - label_cleared
              - label_updated
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: action
                  - name: PR
                  - name: repo
                  - name: sender
                  - name: ssh_url
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                      - name: action
                      - name: PR
                      - name: repo
                      - name: sender
                      - name: ssh_url
                  container:
                    image: docker/whalesay:latest
                    command: [bash]
                    args:
                      - -c
                      - |
                        echo "action: {{inputs.parameters.action}}"
                        echo "PR: {{inputs.parameters.PR}}"
                        echo "repo: {{inputs.parameters.repo}}"
                        echo "sender: {{inputs.parameters.sender}}"
                        echo "ssh_url: {{inputs.parameters.ssh_url}}"
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.action
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataKey: body.pull_request.number
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: test-dep
                dataKey: body.repository.full_name
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: test-dep
                dataKey: body.sender.login
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: test-dep
                dataKey: body.repository.ssh_url
              dest: spec.arguments.parameters.4.value
