---
# https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml
controller:
  metricsConfig:
    enabled: true
server:
  ingress:
    enabled: true
    hosts:
      - argo.localhost
    ingressClassName: kong
  secure: false
  auth:
    enabled: false
artifactRepository:
  archiveLogs: true
  s3:
    accessKeySecret:
      key: accesskey
    secretKeySecret:
      key: secretkey
    insecure: true
    bucket: workflows
    endpoint: minio.minio.svc.cluster.local
    # region:
    # roleARN:
    # useSDKCreds: true
    # encryptionOptions:
    #    enableEncryption: true
